Repository DcentWallet/info, pull requests merged in 2025-02, with the labels that each got.

#403 #402 잘 못 등록된 optimism 맵퍼 수정
  swap-exchange/json/pre/swap-exchange-info-v1.json
  swap-exchange/json/swap-exchange-info-v1.json
Labels: bug

#401 #400: 2025-02-03 지원 코인 업데이트
  supported_coin.json
Labels: Add Token Support

#407 #406 Swap Complete 시에 이벤트 배너 정보 추가
  app/event/README.md
  app/event/app_event_list.json
  app/event/images/event_swap_complete_en.png
  app/event/images/event_swap_complete_en_wide.png
  app/event/images/event_swap_complete_ja.png
  app/event/images/event_swap_complete_ja_wide.png
  app/event/images/event_swap_complete_ko.png
  app/event/images/event_swap_complete_ko_wide.png
Labels: feature

#410 #406: Swap Complete 시에 이벤트 배너 정보 수정
  app/event/README.md
  app/event/app_event_list.json
Labels: enhancement

#413 #411 okx swap 지원 리스트 에서 TRON 제거
  swap-exchange/json/pre/swap-exchange-info-v1.json
Labels: bug

#417 #416: [Add Token] 2025-02-17 고객 지원 토큰 추가 내용 반영
  supported_coin.json
Labels: Add Token Support

#418 [Feature] #414 add filecoin
  firmwareVersion.md
  supported_coin.json
Labels: feature

#421 #420: Constellation의 토큰인 DOR, El paca 아이콘 추가
  images/coins/networks/network_dor.png
  images/coins/networks/network_elpaca.png
Labels: feature
