Repository DcentWallet/info, pull requests merged in 2025-01, with the labels that each got.

#374 [Feature] #373: Kaia token의 badge name 변경
  supported_coin.json
Labels: feature

#376 #375: 지원 코인 목록에서 메인넷이 토큰보다 상위에 위치하도록 순서 변경
  supported_coin.json
Labels: bug

#379 #378: 2025-01-06 지원 코인 업데이트
  supported_coin.json
Labels: Add Token Support

#380 Feature/#377 swap x cmk cgk mapper
  swap-exchange/json/pre/swap-exchange-info.json
Labels: feature

#381 #377 prod 릴리즈
  swap-exchange/json/swap-exchange-info.json
Labels: feature

#385 #384: wallet-models 지원 리스트로 변경
  supported_coin.json
Labels: Add Token Support

#392 #390 CTC FIL NERO SONIC Dapp 상용 릴리즈
  dapp/network_info.json
Labels: feature

#389 #388: 2025-01-20 지원 코인 업데이트
  supported_coin.json
Labels: Add Token Support

#394 #393 KRC20 에서 KLAYTN-ERC20 으로 수정
  swap-exchange/json/pre/swap-exchange-info.json
  swap-exchange/json/swap-exchange-info.json
Labels: bug
