Repository DcentWallet/info, pull requests merged in 2025-05, with the labels that each got.

#470 [Add Token] 2025-05-12 고객 지원 토큰 추가
  supported_coin.json
Labels: Add Token Support

#468 [Feature] #467: Soneium, Scroll 추가
  dapp/images/network_edu_chain.png
  dapp/images/network_scroll.png
  dapp/images/network_soneium.png
  dapp/network_info.json
  images/coins/networks/network_edu_chain.png
  images/coins/networks/network_scroll.png
  images/coins/networks/network_soneium.png
  images/coins/original/asset-conut-1.png
  images/coins/original/asset-counttoken.png
Labels: feature

#471 [Feature] #467 EVM 네트워크 연동 preRelease 제거
  dapp/network_info.json
  images/coins/original/asset-conut_coin.png
  images/coins/original/asset-conuttoken.png
  supported_coin.json
Labels: feature

#473 #472: update supported coin list
  supported_coin.json
Labels: feature

#475 [Feature] #474: Skate (EVM) 프리릴리즈 버전 추가
  dapp/images/network_skate.png
  dapp/network_info.json
  images/coins/networks/network_skate.png
Labels: feature

#477 #474: dapp list의 Skate AMM 위치 변경
  dapp/dapp_list_v2.json
Labels: enhancement

#479 #478 rubic log
  swap-exchange/images/rubic.png
Labels: feature

#482 #481: 로고 업로드
  images/coins/networks/network_hippo.png
Labels: feature

#483 [Feature] #480 update firmware version
  firmwareVersion.md
  supported_coin.json
Labels: feature

#488 #486: 토큰 이미지 업로드
  images/coins/original/asset-wrapped-eeth-berachain.png
Labels: feature
